Hometask2
Anastasia-Nikitina/homework pull request #2
Opened 2020-09-24 18:36 UTC by Anastasia-Nikitina

Домашняя работа 2 *в процессе* 😃

2020-09-25 07:37 UTC, gsvgit requested changes
1) В реквесте должно быть только то, что непосредственно имеет отношение к сдаваемой домашней работе.
2) Так и не нашёл тестов. Может как раз потому, что слишком много лишних файлов.

2020-09-25 07:37 UTC, gsvgit commented on src/homework_2/Functions.fs
> +    let z=y+x
Бинарные операции лучше выделять пробелами.

2020-09-25 07:37 UTC, gsvgit commented on src/homework_2/Functions.fs
> +let third third=
равно тоже лучше отделять пробелом

2020-09-25 07:37 UTC, gsvgit commented on src/homework_2/Functions.fs
> +let third third=
А ещё странно, как у Вас такие имена работают: и функция и аргумент одинаково называются.

2020-09-25 07:37 UTC, gsvgit commented on src/homework_2/Functions.fs
> +    printfn "Введите количество элементов в массиве:"
Ух. Вообще, функция должна принимать свои аргументы и что-то возвращать, а не читать их с консоли.

2020-09-25 07:37 UTC, gsvgit commented on src/homework_2/Functions.fs
> +    arr.[0]=arr.[1]*arr.[0]
Ого, сколько замечаний от системы. Тут явно что-то пошло не так.

2020-09-27 17:52 UTC, Anastasia-Nikitina commented
Это были еще не решенные задачи, там много чего неправильного. Я просто перенастроила репозиторий, поэтому и открыла пул реквест. После занятия в пятницу поняла, что так делать не нужно) 
Можно, пожалуйста, не засчитывать это за попытку сдать домашку?

2020-09-28 17:34 UTC, gsvgit commented
А теперь у Вас все билды лежат. Думаю, в среднем, одна попытка была сделана)

2020-09-30 18:50 UTC, gsvgit requested changes
1) Разберитесь, пожалуйста, с оформлением кода. Мы не просто так это на парпх обсуждали.
2) Постарайтесь отделить сдачу домашки от чистки репозитория. В реквесте слишком много изменеий, не имеющих отношения к сдаваемой домашней работе.

2020-09-30 18:50 UTC, gsvgit commented on src/homework_2/Functions.fs
> +let first x = x*x*x*x + x*x*x + x*x+x + 1
А почему некоторые плюсы отделены пробелами, а некоторые нет?

2020-09-30 18:50 UTC, gsvgit commented on src/homework_2/Program.fs
> +            let res=Functions.first x
А почему где-то у равно есть пробелы, а где-то нет?

2020-10-01 11:55 UTC, Anastasia-Nikitina commented
-Над оформление поработала
-Насчет того, что в реквесте много всего лишнего--поняла, в следующих домашках не буду скидывать все в один реквест:)

2020-10-01 12:12 UTC, gsvgit approved these changes
Пока пусть будет, но вообще, надо быть аккуратнее с оформлением кода.

2020-10-01 12:12 UTC, gsvgit commented on src/homework_2/Program.fs
> +    |First of x:int
Ну и снова беда с форматированием....

2020-10-01 17:01 UTC, merged