homework 3
Anastasia-Nikitina/homework pull request #3
Opened 2020-10-08 17:01 UTC by Anastasia-Nikitina

Выполненная(надеюсь, правильно) домашняя работа номер 3

2020-10-13 06:50 UTC, gsvgit requested changes

2020-10-13 06:50 UTC, gsvgit commented on src/homework_2/FunctionsHw3.fs
> +    let res = Array2D. zeroCreate (a.GetLength 0) (b.GetLength 1)
А правда ли, что размеры входных матриц позволяют их перемножить?

2020-10-13 06:50 UTC, gsvgit commented on src/homework_2/FunctionsHw3.fs
> +let identityMatrix = array2D [|[|1; 0|]; [|0; 1|]|]
Вам нужна единичня матрица произвольного размера, чтобы нормально написать возведение в степень общего вида.

2020-10-13 06:50 UTC, gsvgit commented on src/homework_2/FunctionsHw3.fs
> +          then multMatrix (_go arr (n/2))(_go arr (n/2))
А вычисляете Вы ```_go arr (n/2)``` всё равно два раза. Зачем?

2020-10-13 06:50 UTC, gsvgit commented on src/homework_2/FunctionsHw3.fs
> +    elif n>1
Пробелы. И везде проверьте это.

2020-10-13 06:50 UTC, gsvgit commented on src/homework_2/FunctionsHw3.fs
> +    if n = 0 || n = 1
Как-то сложно у Вас тут с условиями. И работу двойную делаете. Нули, напрмиер, у Вас ещё при инициализации записаны. Кажется, вручную надо только 1 записать и всё.

2020-10-13 18:52 UTC, Anastasia-Nikitina commented on src/homework_2/FunctionsHw3.fs
> +    let res = Array2D. zeroCreate (a.GetLength 0) (b.GetLength 1)
Ну, вроде бы да. А что здесь не так, я не могу понять?

2020-10-13 18:58 UTC, Anastasia-Nikitina commented on src/homework_2/FunctionsHw3.fs
> +let identityMatrix = array2D [|[|1; 0|]; [|0; 1|]|]
То есть, мне надо написать функцию, создающую единичную матрицу размера n*n, где n вводит пользователь? Или дальше в функции возведения в степень указать, что n=2?

2020-10-14 10:20 UTC, gsvgit commented on src/homework_2/FunctionsHw3.fs
> +let identityMatrix = array2D [|[|1; 0|]; [|0; 1|]|]
Не совсем. Функция возведения в степень должна принимать произвольную матрицу и показатель степени. А потом для Финоначчи Вы просто вызываете эту функцию от специальной матрицы. Но чтобы реализовать такое (общего вида) возведение в степень, Вам надо уметь строить единичную матрицу нужного размера. Как --- постарайтесь придумать.

2020-10-15 09:54 UTC, Anastasia-Nikitina commented on src/homework_2/FunctionsHw3.fs
> +          then multMatrix (_go arr (n/2))(_go arr (n/2))
А, я поняла ошибку. Два раза считать _go arr (n/2) неэффективно получается. Исправлю)

2020-10-16 06:49 UTC, gsvgit commented on src/homework_2/FunctionsHw3.fs
> +    let res = Array2D. zeroCreate (a.GetLength 0) (b.GetLength 1)
В общем случае  Вы не любые две матрицы можете перемножить, так что сперва надо просерить, что размеры матриц, поданных на вход, позволяют их перемножить. Это, кстати, говорит о том, что Вы эту функцию саму по себе не пытались тестировать.

2020-10-16 06:55 UTC, gsvgit approved these changes
Зачтено. Есть пара моментов с тем, что у Вас где-то отступ вдруг 2 пробела, а не 4. Выглядит странно, хоть и аккуратно. И пробелы местами потеряны. Кажется, в одном месте Вы принципиально решили не ставить пробелы вокруг умножения. Не надо. В прошлой домашке это было обосновано и красиво. В общем случае это что-то странное.

2020-11-09 12:59 UTC, closed without merging