Homework4
Anastasia-Nikitina/homework pull request #4
Opened 2020-11-09 13:33 UTC by Anastasia-Nikitina

Выполнила домашнюю работу №4

2020-11-10 05:56 UTC, gsvgit requested changes
Будьте аккуратнее с оформлением кода.

2020-11-10 05:56 UTC, gsvgit commented on homework4/ProgramHw4.fs
> +    elif results.Contains BubbleSortList then mainFun (bubbleSortOfList) (readList) (writeList)
А зачем тут столько скобок?

2020-11-10 05:56 UTC, gsvgit commented on homework4/functionsHw4.fs
> +        stringArr.[i] <- (string) array.[i]
Зачем здесь скобки?

2020-11-10 05:56 UTC, gsvgit commented on homework4/functionsHw4.fs
> +let bubbleSortOfArray (arr: array<int>)  =
И всё же, попробуйте убрать лишние указания типов.

2020-11-10 05:56 UTC, gsvgit commented on homework4/functionsHw4.fs
> +            if arr.[j] > arr.[j+1]
Пробелы потеряны.

2020-11-10 05:56 UTC, gsvgit commented on homework4/functionsHw4.fs
> +let bubbleSortOfList (list: int list) =
1) Не нужные указания типов лучше убрать
2) А почему у Вас в двух соседних функциях используется разный синтаксис для указания типов?

2020-11-10 05:56 UTC, gsvgit commented on homework4/functionsHw4.fs
> +        if k <> list2.Length then
И разное оформление условных операторов. Вообще, запись ```if``` и ```then``` на одной строке уместна только если Вы весь условный оператор в одну строку записываете.

2020-11-10 05:56 UTC, gsvgit commented on homework4/functionsHw4.fs
> +    let rec sort (arr: int [], first: int, last: int) =
И ещё один синтаксис для описания типа "массив". Почему так?

2020-11-10 05:56 UTC, gsvgit commented on homework4/functionsHw4.fs
> +    if y >= 0 then  (int64 x <<< 32) +  int64 y
Лишние пробелы (местами два вместо одного).

2020-11-10 05:56 UTC, gsvgit commented on homework4/functionsHw4.fs
> +
Зачем столько пустых строк?

2020-11-10 05:56 UTC, gsvgit commented on homework4/input.txt
> +
Этот файл точно нужен в репозитории?

2020-11-10 05:56 UTC, gsvgit commented on homework4/output.txt
> +
А этот нужен?

2020-11-10 05:56 UTC, gsvgit commented on tests/homework2.Tests/hw3Tests.fs
> +module hw3Tests
Если Вам нужен рефакторинг предыдущеих домашек, делайте его, пожалуйста, отдельно.

2020-11-11 13:23 UTC, Anastasia-Nikitina commented on tests/homework2.Tests/hw3Tests.fs
> +module hw3Tests
я просто не совсем понимаю, как сделать так, чтобы эти изменения были отдельно?

2020-11-11 13:37 UTC, gsvgit commented
Изначально надо было просто не делать их вместе со сдаваемой домашкой.
Можно было сделать в отдельной ветке, например.

Сейчас, видимо, можно откатить коммит, связанный с лишними изменениями и
переложить их в другую ветку.

Regards,
Semyon Grigorev.


ср, 11 нояб. 2020 г. в 16:23, Anastasia-Nikitina <notifications@github.com>:

> *@Anastasia-Nikitina* commented on this pull request.
> ------------------------------
>
> In tests/homework2.Tests/hw3Tests.fs
> <https://github.com/Anastasia-Nikitina/homework/pull/4#discussion_r521354619>
> :
>
> > @@ -0,0 +1,117 @@
>
> +module hw3Tests
>
>
> я просто не совсем понимаю, как сделать так, чтобы эти изменения были
> отдельно?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/Anastasia-Nikitina/homework/pull/4#discussion_r521354619>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA2CQBORGZ2MEK3UJ56LFTSPKF6RANCNFSM4TPLFCUA>
> .
>

2020-11-12 21:31 UTC, closed without merging

2020-11-12 21:31 UTC, Anastasia-Nikitina commented
я сделала отдельную ветку с исправленной четвертой домашкой, поэтому эту закрываю