Homework4 fixes
Anastasia-Nikitina/homework pull request #5
Opened 2020-11-12 20:14 UTC by Anastasia-Nikitina

исправила замечания, надеюсь, теперь все верно :)

2020-11-13 07:39 UTC, gsvgit requested changes
Надо ещё немного поработать над оформлением кода.

2020-11-13 07:39 UTC, gsvgit commented on homework4/functionsHw4.fs
> +let bubbleSortOfArray (arr: array<int>) =
Правда ли, что зедсь важно, что тип элемента --- это int?

2020-11-13 07:39 UTC, gsvgit commented on homework4/functionsHw4.fs
> +    let rec go (list2: list<int>) k =
И здесь тип элемента кажется избыточным

2020-11-13 07:39 UTC, gsvgit commented on homework4/functionsHw4.fs
> +            while (arr.[i] < pivot) do
Лишние скобки

2020-11-13 07:39 UTC, gsvgit commented on homework4/functionsHw4.fs
> +    if y >= 0
Можно так, а можно и вот так:
```
if y >= 0
then (int64 x <<< 32) + int64 y
else (int64 (x + 1) <<< 32) + int64 y
```

2020-11-13 14:24 UTC, Anastasia-Nikitina commented on homework4/functionsHw4.fs
> +let bubbleSortOfArray (arr: array<int>) =
если не указывать int, то все ломается

2020-11-13 14:26 UTC, Anastasia-Nikitina commented on homework4/functionsHw4.fs
> +let bubbleSortOfArray (arr: array<int>) =
а, нет, работает)

2020-11-14 17:42 UTC, gsvgit approved these changes
Зачтено. Но
1) Кажется, в тестах тоже сного где типы не нужны. Может быть даже совсем.
2) Посмотрите ещё разок на оформление условных операторов. Если пользоваться вариантом 
```
if cond
then expr1
else expr2
```
то его ещё много где в коде можно применить.

2020-11-17 10:35 UTC, merged