homework8
Anastasia-Nikitina/homework pull request #7
Opened 2020-12-18 18:31 UTC by Anastasia-Nikitina

2020-12-18 18:38 UTC, Anastasia-Nikitina commented
перепутала номер домашки, это седьмая)

2020-12-21 07:58 UTC, gsvgit requested changes

2020-12-21 07:58 UTC, gsvgit commented on homework7/MyList.fs
> +let rec Map f list =
А почему у Вас функции то с маленькой, то с большой? Например, Map и fold.

2020-12-21 07:58 UTC, gsvgit commented on homework7/MyTree.fs
> +    fold (fun m x -> if x > m then x else m) System.Int32.MinValue tree
Есть такак замечательная стандартная функция ```max```

2020-12-21 07:58 UTC, gsvgit commented on homework7/MyTree.fs
> +    let sum = fold (fun sum x -> sum + x) 0 tree
Отлично. а можете на за два прохода по дереву, а за один?

2020-12-21 07:58 UTC, gsvgit commented on hw7Tests/Program.fs
> +            let list = [1; 2; 3; 4; 5]
А можете добавить тест, где видно, что у фолда с ассоциативностью всё хорошо.

2020-12-21 07:58 UTC, gsvgit commented on hw7Tests/Program.fs
> +        [testCase "Comparision my fold with system fold " <| fun _ ->
Если научиться по обычному списку строить Ваш, то можно propertyTest использовать. Это лучше, чем руками на паре примеров проверять.

2020-12-24 20:57 UTC, Anastasia-Nikitina commented
кажется, все исправила)

2020-12-25 06:39 UTC, gsvgit requested changes

2020-12-25 06:39 UTC, gsvgit commented on homework7/MyList.fs
> +let rec Map f list =
Всё ещё странно, что Вы выбрали такой вариант наименования, хотя видно, что аналогичные сиситемные функции с маленькой буквы. Ну ладно, зато единоообразно)

2020-12-25 06:39 UTC, gsvgit commented on homework7/MyList.fs
> +    | Cons (head, tail) -> [head] @ TransformToSystemList tail
И всё же, почему ```@```,  а не  ```::``` ? Просто 
```
head :: TransformToSystemList tail
```

2020-12-25 06:39 UTC, gsvgit commented on NUnitTestProject1/Tests.fs
> +        [testCase "Associatavity fold " <| fun _ ->
Ну вообще, я имел ввиду что-то типа деления. Сложение в каком направлении не сворачивай, результат один и тот же будет.

2020-12-25 06:39 UTC, gsvgit commented on NUnitTestProject1/Tests.fs
> +    testList "TestPropertyForLists"
Не. Не понял. У Вас два файла с тестами? Зачем? Почему в одном старые названия функций, а в другом не все тесты? Что-то странное происходит.

2020-12-25 06:39 UTC, gsvgit commented on NUnitTestProject1/Tests.fs
> +                Expect.equal (MyList.Fold (fun sum x -> x + sum) 0 (TransformToMyList list))  (List.fold (fun sum x -> x + sum) 0 list)
Можно просто 
```
MyList.Fold (+) 0 ....
```

2020-12-25 06:39 UTC, gsvgit commented on NUnitTestProject1/Tests.fs
> +    testList "TestPropertyForLists"
Или все.... Я запутался) Наведите, пожалуйста, порядок.

2020-12-25 06:52 UTC, Anastasia-Nikitina commented on NUnitTestProject1/Tests.fs
> +    testList "TestPropertyForLists"
я создала новый тестовый проект, а старый удалила
не понимаю, почему не загрузились эти изменения

2020-12-25 06:54 UTC, gsvgit commented on NUnitTestProject1/Tests.fs
> +    testList "TestPropertyForLists"
Вероятно, Вы удалили проект из IDE, а файлы на диске остались.

2020-12-25 09:43 UTC, gsvgit commented on hw7Tests/Tests.fs
> +                Expect.equal (MyList.Fold (fun x y -> x / y) 0 (TransformToMyList (lst)))  (List.fold (fun x y -> x / y) 0 lst)
Свёртка деления с нулём --- это сильно:) И что это нам покажет?

2020-12-25 10:27 UTC, Anastasia-Nikitina commented
так-с, ну вот теперь уж вроде бы точно все))

2020-12-25 10:44 UTC, gsvgit requested changes

2020-12-25 10:44 UTC, gsvgit commented on NUnitTestProject1/Tests.fs
> +                let expected = List.fold (fun x y -> x / y) lst.Head lst.Tail
Ну не только же со сложенеим можно упростить запись fold-а.  И сложение, и деление, и даже умножение --- просто функции от двух аргументов. Потому их и можно не заворачивать ещё раз в анонимную функцию

2020-12-25 10:44 UTC, gsvgit commented on NUnitTestProject1/Tests.fs
> +             else
А где тесты на iter?

2020-12-25 11:21 UTC, gsvgit approved these changes

2020-12-25 11:23 UTC, merged