Really homework8
Anastasia-Nikitina/homework pull request #8
Opened 2021-02-27 16:29 UTC by Anastasia-Nikitina

домашняя работа №8, задания №2-3

2021-02-27 18:40 UTC, gsvgit requested changes
Про сложение и умножение два общих замечания.
1) Вы забываете проверять, что в результате операций может получиться нейтральный элемент, который мы не храним.
2) Лучше сразу делать обобщённые операции, так как дальше в автоматах Вам разные полукольца понадобятся.

2021-02-27 18:40 UTC, gsvgit commented on homework8/matrices.fs
> +                arr.[i / y, i % y] <-  arr.[i / y, i % y] + (int numbers.[i].[j] - 48) * int (10.0 ** float (numbers.[i].Length - 1 - j))
А что за магические константы 48 и 10 ?

2021-02-27 18:40 UTC, gsvgit commented on homework8/matrices.fs
> +    match (m1, m2) with
Что-то тут многовато ругони от компилятора.

2021-03-03 09:25 UTC, Anastasia-Nikitina commented on homework8/matrices.fs
> +                arr.[i / y, i % y] <-  arr.[i / y, i % y] + (int numbers.[i].[j] - 48) * int (10.0 ** float (numbers.[i].Length - 1 - j))
Ну 48 - это код нуля в ASCII, использовала его чтобы переводить посимвольно из строки в инт. 10 в какой-то степени для этого же. Но сейчас поняла, что, кажется, для строки и без этих махинаций все работает)

2021-03-03 09:26 UTC, Anastasia-Nikitina commented on homework8/matrices.fs
> +                arr.[i / y, i % y] <-  arr.[i / y, i % y] + (int numbers.[i].[j] - 48) * int (10.0 ** float (numbers.[i].Length - 1 - j))
А обобщенные операции это как?

2021-03-10 11:32 UTC, gsvgit commented on homework8/matrices.fs
> +                arr.[i / y, i % y] <-  arr.[i / y, i % y] + (int numbers.[i].[j] - 48) * int (10.0 ** float (numbers.[i].Length - 1 - j))
Это я про то, что опреации над матрицами можно параметризовать моноидом или полукольцом (или ещё чем), чтобы знать, как выглядят элементраные операции и кто такой нейтральный элемент.

2021-04-01 06:49 UTC, gsvgit requested changes

2021-04-01 06:49 UTC, gsvgit commented on homework8/matrices.fs
> +        match (m1, m2) with
Коапилятор намекает, что сопоставление не полное, некоторые варианты упущены.

2021-04-01 06:49 UTC, gsvgit commented on homework8/matrices.fs
> +        |(a, None) -> None
Такие варианты можно объединять:
```
| (a, None) | (None, a ) -> None
```

2021-04-01 06:49 UTC, gsvgit commented on homework8/matrices.fs
> +        |(Leaf x, Node(a, b, c, d)) -> Node (numberToMatrix x a algStr, numberToMatrix x b algStr, numberToMatrix x c algStr, numberToMatrix x d algStr)
Кажется, тут правые части тоже одинаковые, стало быть, эти два шаблона тоже можно объёдинить.

2021-04-20 11:14 UTC, gsvgit requested changes

2021-04-20 11:14 UTC, gsvgit commented on homework8/matrices.fs
> +            let NW = Array2D.zeroCreate x x
Наверное, так тоже работает, но посмотрите, Вы создаёте пачку новых массивов только для того, чтобы их потом выкинуть. И так на каждой итерации. Не проще ли просто вычислять индексы? Примерно, как в быстрой сортировке.

2021-04-20 11:14 UTC, gsvgit commented on hw8Test/Tests.fs
> +          a.[i, j] <- (new System.Random()).Next (-10, 10)
Генератор случайных чисел надо создать один раз, а потом им пользоваться.

2021-04-20 11:14 UTC, gsvgit commented on hw8Test/Tests.fs
> +             let res = (add m1 m2 semiRing).qt
А почему Вы только деревья сравниваете, а не целиком структуры? Они же абсолютно идентичными должны быть.

2021-04-21 18:50 UTC, Anastasia-Nikitina commented on hw8Test/Tests.fs
> +             let res = (add m1 m2 semiRing).qt
так тесты работать не хотят, хотя они и правда идентичны

2021-04-21 18:50 UTC, Anastasia-Nikitina commented on homework8/matrices.fs
> +            let NW = Array2D.zeroCreate x x
не совсем поняла, что значит, высчитывать индексы, как тут это поможет? и еще я же не просто так "выкидываю" массивы, я записываю в них значения из матрицы и потом переиспользую дальше

2021-04-21 18:56 UTC, gsvgit commented on hw8Test/Tests.fs
> +             let res = (add m1 m2 semiRing).qt
М... Мне кажется, или это означает, что что-то всё таки не так?

2021-04-21 18:59 UTC, gsvgit commented on homework8/matrices.fs
> +            let NW = Array2D.zeroCreate x x
Зачем Вам эти массивы как отдельные объекты? Почему они не могут остаться кусками исходного массива? Более того, зная индекс ячейки Вы можете однозначно определить её место в дереве квадрантов. Зачем создавать огромное количество промежуточных сущностей?

2021-04-21 19:01 UTC, Anastasia-Nikitina commented on hw8Test/Tests.fs
> +             let res = (add m1 m2 semiRing).qt
я просто действительно не знаю, что может быть не так, все остальное работает как надо. 
проверяли на другой программе, также адекватно может сравнивать только деревья.

2021-04-21 19:02 UTC, Anastasia-Nikitina commented on hw8Test/Tests.fs
> +          a.[i, j] <- (new System.Random()).Next (-10, 10)
а я вроде бы так и сделала. эту функцию дальше только вызываю непосредственно в тестах

2021-04-26 07:42 UTC, gsvgit requested changes

2021-04-26 07:42 UTC, gsvgit commented on homework8/matrices.fs
> +    struct
Если что, Вы могли просто к тому, что у Вас было написано до этого, сверху приписть ```[<Struct>]```
```
[<Struct>]
type T = ....
```

2021-04-26 07:42 UTC, gsvgit commented on homework8/matrices.fs
> +let readAndExtension file =
Не понимаю. Зачем Вы смешиваете два рвзных действия в одну функцию?

2021-04-26 07:42 UTC, gsvgit commented on homework8/matrices.fs
> +let rec goAdd (m1: QuadTree<int>) (m2: QuadTree<int>) (algStr: SemiRing<int>) =
А почему такие вещи не вложенные функции?

2021-04-26 07:42 UTC, gsvgit commented on hw8Test/Tests.fs
> +let rand = (new System.Random()).Next (-10, 10)
Что?) Как-то Вы слишком радикально поступили.

2021-04-26 07:42 UTC, gsvgit commented on hw8Test/Tests.fs
> +    let a = Array2D.zeroCreate 2 2
Ага. И случайный массив всегда одного и того же размера. Интеренсо...

2021-04-26 07:42 UTC, gsvgit commented on hw8Test/Tests.fs
> +        [testProperty "Comparision add QT with add arrays" <| fun _ ->
Почему бы не использовать аргумент функции как, напрмиер, случайное значение для размера матриц?

2021-04-28 13:57 UTC, Anastasia-Nikitina commented on homework8/matrices.fs
> +let rec goAdd (m1: QuadTree<int>) (m2: QuadTree<int>) (algStr: SemiRing<int>) =
потому что goAdd я потом вызываю в умножении матриц еще

2021-04-28 14:21 UTC, Anastasia-Nikitina commented on homework8/matrices.fs
> +let readAndExtension file =
Так удобнее, в любом случае нужно проверять матрицу на то, подходящие ли у нее размеры, а тут и дополняем сразу, в случае чего

2021-04-29 06:31 UTC, gsvgit commented on homework8/matrices.fs
> +let rec goAdd (m1: QuadTree<int>) (m2: QuadTree<int>) (algStr: SemiRing<int>) =
А. Не заметил. Хорошо.

2021-04-30 14:00 UTC, gsvgit commented on hw8Test/Tests.fs
> +    let rand = (new System.Random()).Next (-10, 10)
А зачем Вы всё одним и тем же значением инициализируете? Вот я про что. Вынести создание генератора на самый верх --- хорошая была идея. Но почему всегда одно и то же значение?

2021-04-30 14:05 UTC, Anastasia-Nikitina commented on hw8Test/Tests.fs
> +        [testProperty "Comparision add QT with add arrays" <| fun _ ->
там возникают проблемы с тензорным умножением при больших размерах матриц

2021-04-30 14:38 UTC, gsvgit commented on hw8Test/Tests.fs
> +        [testProperty "Comparision add QT with add arrays" <| fun _ ->
Так можно же нормировать внутри.

2021-04-30 15:01 UTC, Anastasia-Nikitina commented
никак не могу понять, почему в vs тесты проходят, а здесь рушатся?

2021-04-30 15:08 UTC, gsvgit commented
Вероятно, случайность играет свою роль. Падение выглядит адекватным в том смысле, что не похоже на то, что что-то прям сломалось. Возможно, попался просто параметр на котором не работает. Подумайте, где у Вас обращение к массиву по индексу и почеиу там что-то может пойти не так.

2021-04-30 15:18 UTC, gsvgit commented
У Вас в сообщении об ошибке даже указано, откуда можно начать: homework/homework/homework8/matrices.fs:line 43

2021-05-02 13:26 UTC, Anastasia-Nikitina commented
Пересобирала несколько раз, и обычно здесь показывает, что ломается сложение на значениях +-2. В visual studio на этих значениях все работает хорошо. Еще я проверила места, где может быть выход за границы массива, там вроде как ошибок тоже нет

2021-05-03 16:58 UTC, Anastasia-Nikitina commented
Если никаких других ошибок нет, можно закрыть реквест без тестов? По сути ведь, все работает, почему именно на гитхабе все ломается-я не знаю.

2021-05-05 16:46 UTC, gsvgit requested changes

2021-05-05 16:46 UTC, gsvgit commented on homework12/hw12.fs
> +                if m.[i, j] = null
У Вас эти блоки кода повтаряются раза 3 с незначительными модификациями. Может можно как-то упростить весь генератор?

2021-05-05 16:46 UTC, gsvgit commented on homework12/hw12.fs
> +let QTmultParallel (m1: QTwithSize) (m2: QTwithSize) (algStr: SemiRing<int>) p =
А почему это не в QTree живёт?

2021-05-05 16:46 UTC, gsvgit commented on hw8Test/Tests.fs
> +[<Tests>]
А на параллельность тесты?

2021-05-24 06:11 UTC, gsvgit approved these changes

2021-05-24 06:11 UTC, gsvgit commented on GeneratorOfSparseMatrices/Program.fs
> +open System
Обратите внимание, что такое подход делает Ваше решение не композициональным: я не мого его запустить из внешнего скрипта. Так что лучше что-то типа Argu использовать. Но тут дело не в инструменте, а в способе взаимодействия с пользователем.

2021-05-24 06:11 UTC, gsvgit commented on GeneratorOfSparseMatrices/generator.fs
> +                k <- k + 1
Прадва ли, что инкременит k можно вынести за if-ы?

2021-05-24 06:11 UTC, gsvgit commented on homework8/matrices.fs
> +    let rec go (m: int [,]) =
Красиво выглядит.

2021-09-13 09:29 UTC, merged